// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArIdSOn4Idsy5JBiPizhs7Z4jRIagCoMI',
    appId: '1:909168735984:web:77687337e92114d3d2f435',
    messagingSenderId: '909168735984',
    projectId: 'flutterauth-512d4',
    authDomain: 'flutterauth-512d4.firebaseapp.com',
    storageBucket: 'flutterauth-512d4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWI5qItqr3t6CBdlz23i-x9KIw8aYEXco',
    appId: '1:909168735984:android:11303705201d5e92d2f435',
    messagingSenderId: '909168735984',
    projectId: 'flutterauth-512d4',
    storageBucket: 'flutterauth-512d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTwDId7OwjT-6V_6X4EBJvEsi8ROu71D8',
    appId: '1:909168735984:ios:39f13c038f8d5247d2f435',
    messagingSenderId: '909168735984',
    projectId: 'flutterauth-512d4',
    storageBucket: 'flutterauth-512d4.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTwDId7OwjT-6V_6X4EBJvEsi8ROu71D8',
    appId: '1:909168735984:ios:39f13c038f8d5247d2f435',
    messagingSenderId: '909168735984',
    projectId: 'flutterauth-512d4',
    storageBucket: 'flutterauth-512d4.firebasestorage.app',
    iosBundleId: 'com.example.galleriaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArIdSOn4Idsy5JBiPizhs7Z4jRIagCoMI',
    appId: '1:909168735984:web:16da67a004525f24d2f435',
    messagingSenderId: '909168735984',
    projectId: 'flutterauth-512d4',
    authDomain: 'flutterauth-512d4.firebaseapp.com',
    storageBucket: 'flutterauth-512d4.firebasestorage.app',
  );

}